// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SprintStatus string

const (
	SprintStatusPlanned   SprintStatus = "planned"
	SprintStatusActive    SprintStatus = "active"
	SprintStatusCompleted SprintStatus = "completed"
)

func (e *SprintStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SprintStatus(s)
	case string:
		*e = SprintStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SprintStatus: %T", src)
	}
	return nil
}

type NullSprintStatus struct {
	SprintStatus SprintStatus `json:"sprint_status"`
	Valid        bool         `json:"valid"` // Valid is true if SprintStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSprintStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SprintStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SprintStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSprintStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SprintStatus), nil
}

type Sprint struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ProjectID          pgtype.UUID        `db:"project_id" json:"project_id"`
	Name               string             `db:"name" json:"name"`
	Goal               pgtype.Text        `db:"goal" json:"goal"`
	Status             SprintStatus       `db:"status" json:"status"`
	PlannedStartedAt   pgtype.Timestamptz `db:"planned_started_at" json:"planned_started_at"`
	PlannedCompletedAt pgtype.Timestamptz `db:"planned_completed_at" json:"planned_completed_at"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
