// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSprint = `-- name: CompleteSprint :one
UPDATE sprints
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
`

func (q *Queries) CompleteSprint(ctx context.Context, id pgtype.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, completeSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.PlannedStartedAt,
		&i.PlannedCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (project_id, name, goal, status, planned_started_at, planned_completed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
`

type CreateSprintParams struct {
	ProjectID          pgtype.UUID        `db:"project_id" json:"project_id"`
	Name               string             `db:"name" json:"name"`
	Goal               pgtype.Text        `db:"goal" json:"goal"`
	Status             SprintStatus       `db:"status" json:"status"`
	PlannedStartedAt   pgtype.Timestamptz `db:"planned_started_at" json:"planned_started_at"`
	PlannedCompletedAt pgtype.Timestamptz `db:"planned_completed_at" json:"planned_completed_at"`
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ProjectID,
		arg.Name,
		arg.Goal,
		arg.Status,
		arg.PlannedStartedAt,
		arg.PlannedCompletedAt,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.PlannedStartedAt,
		&i.PlannedCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSprint = `-- name: DeleteSprint :one
UPDATE sprints
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteSprint(ctx context.Context, id pgtype.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, deleteSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.PlannedStartedAt,
		&i.PlannedCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSprint = `-- name: GetSprint :one
SELECT id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
FROM sprints
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSprint(ctx context.Context, id pgtype.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.PlannedStartedAt,
		&i.PlannedCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteSprint = `-- name: HardDeleteSprint :exec
DELETE FROM sprints
WHERE id = $1
`

func (q *Queries) HardDeleteSprint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteSprint, id)
	return err
}

const listSprintsByProject = `-- name: ListSprintsByProject :many
SELECT id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
FROM sprints
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSprintsByProject(ctx context.Context, projectID pgtype.UUID) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Goal,
			&i.Status,
			&i.PlannedStartedAt,
			&i.PlannedCompletedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByProjectPaged = `-- name: ListSprintsByProjectPaged :many
WITH filtered_sprints AS (
  SELECT
    id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at,
    COUNT(*) OVER () as total_count
  FROM
    sprints
  WHERE
    project_id = $1 AND deleted_at IS NULL
    AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
)
SELECT
  id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at, total_count
FROM
  filtered_sprints
ORDER BY
  created_at DESC
LIMIT $3
OFFSET $4
`

type ListSprintsByProjectPagedParams struct {
	ProjectID pgtype.UUID `db:"project_id" json:"project_id"`
	Column2   string      `db:"column_2" json:"column_2"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

type ListSprintsByProjectPagedRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ProjectID          pgtype.UUID        `db:"project_id" json:"project_id"`
	Name               string             `db:"name" json:"name"`
	Goal               pgtype.Text        `db:"goal" json:"goal"`
	Status             SprintStatus       `db:"status" json:"status"`
	PlannedStartedAt   pgtype.Timestamptz `db:"planned_started_at" json:"planned_started_at"`
	PlannedCompletedAt pgtype.Timestamptz `db:"planned_completed_at" json:"planned_completed_at"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TotalCount         int64              `db:"total_count" json:"total_count"`
}

func (q *Queries) ListSprintsByProjectPaged(ctx context.Context, arg ListSprintsByProjectPagedParams) ([]ListSprintsByProjectPagedRow, error) {
	rows, err := q.db.Query(ctx, listSprintsByProjectPaged,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintsByProjectPagedRow{}
	for rows.Next() {
		var i ListSprintsByProjectPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Goal,
			&i.Status,
			&i.PlannedStartedAt,
			&i.PlannedCompletedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSprint = `-- name: StartSprint :one
UPDATE sprints
SET status = 'active', started_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
`

func (q *Queries) StartSprint(ctx context.Context, id pgtype.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, startSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.PlannedStartedAt,
		&i.PlannedCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET name = $2, goal = $3, status = $4, planned_started_at = $5, planned_completed_at = $6, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, goal, status, planned_started_at, planned_completed_at, started_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateSprintParams struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Name               string             `db:"name" json:"name"`
	Goal               pgtype.Text        `db:"goal" json:"goal"`
	Status             SprintStatus       `db:"status" json:"status"`
	PlannedStartedAt   pgtype.Timestamptz `db:"planned_started_at" json:"planned_started_at"`
	PlannedCompletedAt pgtype.Timestamptz `db:"planned_completed_at" json:"planned_completed_at"`
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.Status,
		arg.PlannedStartedAt,
		arg.PlannedCompletedAt,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.Status,
		&i.PlannedStartedAt,
		&i.PlannedCompletedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
