// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateBoardColumns = `-- name: BulkCreateBoardColumns :many
WITH column_data AS (
  SELECT
    $1::uuid as board_id,
    $2::text[] as names,
    $3::int4[] as positions
)
INSERT INTO board_columns (board_id, name, position)
SELECT
  board_id,
  names[idx],
  positions[idx]
FROM column_data, generate_series(1, array_length(names, 1)) AS idx
RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type BulkCreateBoardColumnsParams struct {
	Column1 pgtype.UUID `db:"column_1" json:"column_1"`
	Column2 []string    `db:"column_2" json:"column_2"`
	Column3 []int32     `db:"column_3" json:"column_3"`
}

func (q *Queries) BulkCreateBoardColumns(ctx context.Context, arg BulkCreateBoardColumnsParams) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, bulkCreateBoardColumns, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardColumn{}
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (sprint_id, name)
VALUES ($1, $2)
RETURNING id, sprint_id, name, created_at, updated_at, deleted_at
`

type CreateBoardParams struct {
	SprintID pgtype.UUID `db:"sprint_id" json:"sprint_id"`
	Name     string      `db:"name" json:"name"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.SprintID, arg.Name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBoardColumn = `-- name: CreateBoardColumn :one
INSERT INTO board_columns (board_id, name, position)
VALUES ($1, $2, (SELECT COALESCE(MAX(position), -1) + 1 FROM board_columns WHERE board_id = $1 AND deleted_at IS NULL))
RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type CreateBoardColumnParams struct {
	BoardID pgtype.UUID `db:"board_id" json:"board_id"`
	Name    string      `db:"name" json:"name"`
}

func (q *Queries) CreateBoardColumn(ctx context.Context, arg CreateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createBoardColumn, arg.BoardID, arg.Name)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :one
UPDATE boards SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, sprint_id, name, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteBoard(ctx context.Context, id pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, deleteBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBoardColumn = `-- name: DeleteBoardColumn :one
UPDATE board_columns SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteBoardColumn(ctx context.Context, id pgtype.UUID) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, deleteBoardColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, sprint_id, name, created_at, updated_at, deleted_at FROM boards WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBoard(ctx context.Context, id pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBoardColumn = `-- name: GetBoardColumn :one
SELECT id, board_id, name, position, created_at, updated_at, deleted_at FROM board_columns WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBoardColumn(ctx context.Context, id pgtype.UUID) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getBoardColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBoardColumns = `-- name: ListBoardColumns :many
SELECT id, board_id, name, position, created_at, updated_at, deleted_at FROM board_columns WHERE board_id = $1 AND deleted_at IS NULL ORDER BY position ASC
`

func (q *Queries) ListBoardColumns(ctx context.Context, boardID pgtype.UUID) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listBoardColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardColumn{}
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardColumnsPaged = `-- name: ListBoardColumnsPaged :many
WITH filtered_columns AS (
  SELECT
    id, board_id, name, position, created_at, updated_at, deleted_at,
    COUNT(*) OVER () as total_count
  FROM
    board_columns
  WHERE
    deleted_at IS NULL
    AND (array_length($1::uuid[], 1) IS NULL OR id = ANY($1::uuid[]))
    AND (array_length($2::uuid[], 1) IS NULL OR board_id = ANY($2::uuid[]))
    AND ($3::text = '' OR name ILIKE '%' || $3 || '%')
)
SELECT
  id, board_id, name, position, created_at, updated_at, deleted_at, total_count
FROM
  filtered_columns
ORDER BY
  position ASC
LIMIT $4
OFFSET $5
`

type ListBoardColumnsPagedParams struct {
	Column1 []pgtype.UUID `db:"column_1" json:"column_1"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
	Column3 string        `db:"column_3" json:"column_3"`
	Limit   int32         `db:"limit" json:"limit"`
	Offset  int32         `db:"offset" json:"offset"`
}

type ListBoardColumnsPagedRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	BoardID    pgtype.UUID        `db:"board_id" json:"board_id"`
	Name       string             `db:"name" json:"name"`
	Position   int32              `db:"position" json:"position"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TotalCount int64              `db:"total_count" json:"total_count"`
}

func (q *Queries) ListBoardColumnsPaged(ctx context.Context, arg ListBoardColumnsPagedParams) ([]ListBoardColumnsPagedRow, error) {
	rows, err := q.db.Query(ctx, listBoardColumnsPaged,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardColumnsPagedRow{}
	for rows.Next() {
		var i ListBoardColumnsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsBySprint = `-- name: ListBoardsBySprint :many
SELECT id, sprint_id, name, created_at, updated_at, deleted_at FROM boards WHERE sprint_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListBoardsBySprint(ctx context.Context, sprintID pgtype.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoardsBySprint, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsPaged = `-- name: ListBoardsPaged :many
WITH applicable_sprints AS (
  -- If projectId is provided, get all sprints for those projects
  -- If projectId is not provided, this CTE returns all non-deleted sprints
  SELECT id
  FROM sprints
  WHERE
    deleted_at IS NULL
    AND (array_length($2::uuid[], 1) IS NULL OR project_id = ANY($2::uuid[]))
),
filtered_boards AS (
  SELECT
    b.id, b.sprint_id, b.name, b.created_at, b.updated_at, b.deleted_at,
    COUNT(*) OVER () as total_count
  FROM
    boards b
  WHERE
    b.deleted_at IS NULL
    -- Filter by board IDs if provided
    AND (array_length($1::uuid[], 1) IS NULL OR b.id = ANY($1::uuid[]))
    -- Filter by sprint ID if provided, otherwise use applicable sprints from project filter
    AND (
      CASE
        WHEN array_length($3::uuid[], 1) IS NOT NULL THEN b.sprint_id = ANY($3::uuid[])
        ELSE b.sprint_id IN (SELECT id FROM applicable_sprints)
      END
    )
    -- Filter by name if provided
    AND ($4::text = '' OR b.name ILIKE '%' || $4 || '%')
)
SELECT
  id, sprint_id, name, created_at, updated_at, deleted_at, total_count
FROM
  filtered_boards
LIMIT $5
OFFSET $6
`

type ListBoardsPagedParams struct {
	Column1 []pgtype.UUID `db:"column_1" json:"column_1"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
	Column3 []pgtype.UUID `db:"column_3" json:"column_3"`
	Column4 string        `db:"column_4" json:"column_4"`
	Limit   int32         `db:"limit" json:"limit"`
	Offset  int32         `db:"offset" json:"offset"`
}

type ListBoardsPagedRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	SprintID   pgtype.UUID        `db:"sprint_id" json:"sprint_id"`
	Name       string             `db:"name" json:"name"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TotalCount int64              `db:"total_count" json:"total_count"`
}

func (q *Queries) ListBoardsPaged(ctx context.Context, arg ListBoardsPagedParams) ([]ListBoardsPagedRow, error) {
	rows, err := q.db.Query(ctx, listBoardsPaged,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardsPagedRow{}
	for rows.Next() {
		var i ListBoardsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderBoardColumn = `-- name: ReorderBoardColumn :one
UPDATE board_columns SET position = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type ReorderBoardColumnParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Position int32       `db:"position" json:"position"`
}

func (q *Queries) ReorderBoardColumn(ctx context.Context, arg ReorderBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, reorderBoardColumn, arg.ID, arg.Position)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const reorderBoardColumnsInBatch = `-- name: ReorderBoardColumnsInBatch :many
WITH validation AS (
  -- Validate: all provided IDs exist and belong to this board
  SELECT id, ROW_NUMBER() OVER () - 1 as pos
  FROM UNNEST($2::uuid[]) AS t(id)
  WHERE EXISTS (
    SELECT 1 FROM board_columns bc
    WHERE bc.id = t.id AND bc.board_id = $1 AND bc.deleted_at IS NULL
  )
),updated AS (
  UPDATE board_columns
  SET position = validation.pos, updated_at = NOW()
  FROM validation
  WHERE board_columns.id = validation.id
    AND board_columns.board_id = $1
    AND board_columns.deleted_at IS NULL
    -- Validate: provided count matches total columns in board
    AND (
      SELECT COUNT(*) FROM board_columns
      WHERE board_id = $1 AND deleted_at IS NULL
    ) = array_length($2::uuid[], 1)
    -- Validate: all array elements are valid columns for this board
    AND (
      SELECT COUNT(*) FROM validation
    ) = array_length($2::uuid[], 1)
  RETURNING board_columns.id, board_columns.board_id, board_columns.name, board_columns.position, board_columns.created_at, board_columns.updated_at, board_columns.deleted_at
)
SELECT id, board_id, name, position, created_at, updated_at, deleted_at FROM updated ORDER BY position
`

type ReorderBoardColumnsInBatchParams struct {
	BoardID pgtype.UUID   `db:"board_id" json:"board_id"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
}

type ReorderBoardColumnsInBatchRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	BoardID   pgtype.UUID        `db:"board_id" json:"board_id"`
	Name      string             `db:"name" json:"name"`
	Position  int32              `db:"position" json:"position"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Atomically validates and reorders columns with row-level locking
// Results ordered by position to maintain input array order
func (q *Queries) ReorderBoardColumnsInBatch(ctx context.Context, arg ReorderBoardColumnsInBatchParams) ([]ReorderBoardColumnsInBatchRow, error) {
	rows, err := q.db.Query(ctx, reorderBoardColumnsInBatch, arg.BoardID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReorderBoardColumnsInBatchRow{}
	for rows.Next() {
		var i ReorderBoardColumnsInBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = $2, sprint_id = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, sprint_id, name, created_at, updated_at, deleted_at
`

type UpdateBoardParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	SprintID pgtype.UUID `db:"sprint_id" json:"sprint_id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.ID, arg.Name, arg.SprintID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBoardColumn = `-- name: UpdateBoardColumn :one
UPDATE board_columns SET name = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type UpdateBoardColumnParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) UpdateBoardColumn(ctx context.Context, arg UpdateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, updateBoardColumn, arg.ID, arg.Name)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
