// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (sprint_id, name, position)
VALUES ($1, $2, (SELECT COALESCE(MAX(position), -1) + 1 FROM boards WHERE sprint_id = $1 AND deleted_at IS NULL))
RETURNING id, sprint_id, name, position, created_at, updated_at, deleted_at
`

type CreateBoardParams struct {
	SprintID pgtype.UUID `db:"sprint_id" json:"sprint_id"`
	Name     string      `db:"name" json:"name"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.SprintID, arg.Name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBoardColumn = `-- name: CreateBoardColumn :one
INSERT INTO board_columns (board_id, name, position)
VALUES ($1, $2, (SELECT COALESCE(MAX(position), -1) + 1 FROM board_columns WHERE board_id = $1 AND deleted_at IS NULL))
RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type CreateBoardColumnParams struct {
	BoardID pgtype.UUID `db:"board_id" json:"board_id"`
	Name    string      `db:"name" json:"name"`
}

func (q *Queries) CreateBoardColumn(ctx context.Context, arg CreateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createBoardColumn, arg.BoardID, arg.Name)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :one
UPDATE boards SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, sprint_id, name, position, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteBoard(ctx context.Context, id pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, deleteBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBoardColumn = `-- name: DeleteBoardColumn :one
UPDATE board_columns SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteBoardColumn(ctx context.Context, id pgtype.UUID) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, deleteBoardColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, sprint_id, name, position, created_at, updated_at, deleted_at FROM boards WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBoard(ctx context.Context, id pgtype.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBoardColumn = `-- name: GetBoardColumn :one
SELECT id, board_id, name, position, created_at, updated_at, deleted_at FROM board_columns WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBoardColumn(ctx context.Context, id pgtype.UUID) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getBoardColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBoardColumns = `-- name: ListBoardColumns :many
SELECT id, board_id, name, position, created_at, updated_at, deleted_at FROM board_columns WHERE board_id = $1 AND deleted_at IS NULL ORDER BY position ASC
`

func (q *Queries) ListBoardColumns(ctx context.Context, boardID pgtype.UUID) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listBoardColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardColumn{}
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardsBySprint = `-- name: ListBoardsBySprint :many
SELECT id, sprint_id, name, position, created_at, updated_at, deleted_at FROM boards WHERE sprint_id = $1 AND deleted_at IS NULL ORDER BY position ASC
`

func (q *Queries) ListBoardsBySprint(ctx context.Context, sprintID pgtype.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoardsBySprint, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderBoard = `-- name: ReorderBoard :one
UPDATE boards SET position = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, sprint_id, name, position, created_at, updated_at, deleted_at
`

type ReorderBoardParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Position int32       `db:"position" json:"position"`
}

func (q *Queries) ReorderBoard(ctx context.Context, arg ReorderBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, reorderBoard, arg.ID, arg.Position)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const reorderBoardColumn = `-- name: ReorderBoardColumn :one
UPDATE board_columns SET position = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type ReorderBoardColumnParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Position int32       `db:"position" json:"position"`
}

func (q *Queries) ReorderBoardColumn(ctx context.Context, arg ReorderBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, reorderBoardColumn, arg.ID, arg.Position)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const reorderBoardColumnsInBatch = `-- name: ReorderBoardColumnsInBatch :many
WITH validation AS (
  -- Validate: all provided IDs exist and belong to this board
  SELECT id, ROW_NUMBER() OVER () - 1 as pos
  FROM UNNEST($2::uuid[]) AS t(id)
  WHERE EXISTS (
    SELECT 1 FROM board_columns bc
    WHERE bc.id = t.id AND bc.board_id = $1 AND bc.deleted_at IS NULL
  )
),updated AS (
  UPDATE board_columns
  SET position = validation.pos, updated_at = NOW()
  FROM validation
  WHERE board_columns.id = validation.id
    AND board_columns.board_id = $1
    AND board_columns.deleted_at IS NULL
    -- Validate: provided count matches total columns in board
    AND (
      SELECT COUNT(*) FROM board_columns
      WHERE board_id = $1 AND deleted_at IS NULL
    ) = array_length($2::uuid[], 1)
    -- Validate: all array elements are valid columns for this board
    AND (
      SELECT COUNT(*) FROM validation
    ) = array_length($2::uuid[], 1)
  RETURNING board_columns.id, board_columns.board_id, board_columns.name, board_columns.position, board_columns.created_at, board_columns.updated_at, board_columns.deleted_at
)
SELECT id, board_id, name, position, created_at, updated_at, deleted_at FROM updated ORDER BY position
`

type ReorderBoardColumnsInBatchParams struct {
	BoardID pgtype.UUID   `db:"board_id" json:"board_id"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
}

type ReorderBoardColumnsInBatchRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	BoardID   pgtype.UUID        `db:"board_id" json:"board_id"`
	Name      string             `db:"name" json:"name"`
	Position  int32              `db:"position" json:"position"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Atomically validates and reorders columns with row-level locking
// Results ordered by position to maintain input array order
func (q *Queries) ReorderBoardColumnsInBatch(ctx context.Context, arg ReorderBoardColumnsInBatchParams) ([]ReorderBoardColumnsInBatchRow, error) {
	rows, err := q.db.Query(ctx, reorderBoardColumnsInBatch, arg.BoardID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReorderBoardColumnsInBatchRow{}
	for rows.Next() {
		var i ReorderBoardColumnsInBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = $2, sprint_id = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, sprint_id, name, position, created_at, updated_at, deleted_at
`

type UpdateBoardParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	SprintID pgtype.UUID `db:"sprint_id" json:"sprint_id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.ID, arg.Name, arg.SprintID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBoardColumn = `-- name: UpdateBoardColumn :one
UPDATE board_columns SET name = $2, updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL RETURNING id, board_id, name, position, created_at, updated_at, deleted_at
`

type UpdateBoardColumnParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

func (q *Queries) UpdateBoardColumn(ctx context.Context, arg UpdateBoardColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, updateBoardColumn, arg.ID, arg.Name)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
