// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgMembers = `-- name: CountOrgMembers :one
SELECT
    COUNT(*)
FROM
    org_members om
    JOIN users u ON u.id = om.user_id
WHERE
    om.org_id = $1
    AND ($2::text = '' OR u.email ILIKE '%' || $2 || '%')
    AND ($3::text = '' OR u.display_name ILIKE '%' || $3 || '%')
`

type CountOrgMembersParams struct {
	OrgID   pgtype.UUID `db:"org_id" json:"org_id"`
	Column2 string      `db:"column_2" json:"column_2"`
	Column3 string      `db:"column_3" json:"column_3"`
}

func (q *Queries) CountOrgMembers(ctx context.Context, arg CountOrgMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgMembers, arg.OrgID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO
    orgs (name, slug)
VALUES
    ($1, $2)
RETURNING
    id, name, slug, created_at, updated_at
`

type CreateOrgParams struct {
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
}

type CreateOrgRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Slug)
	var i CreateOrgRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrgMember = `-- name: CreateOrgMember :one
INSERT INTO
    org_members (org_id, user_id, role)
VALUES
    ($1, $2, $3)
RETURNING
    org_id, user_id, role, joined_at
`

type CreateOrgMemberParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Role   OrgRole     `db:"role" json:"role"`
}

func (q *Queries) CreateOrgMember(ctx context.Context, arg CreateOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, createOrgMember, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
UPDATE orgs
SET
    deleted_at = NOW()
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteOrg(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const deleteOrgMember = `-- name: DeleteOrgMember :exec
DELETE FROM org_members
WHERE
    org_id = $1
    AND user_id = $2
`

type DeleteOrgMemberParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteOrgMember(ctx context.Context, arg DeleteOrgMemberParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMember, arg.OrgID, arg.UserID)
	return err
}

const getOrgById = `-- name: GetOrgById :one
SELECT
    id, name, slug, created_at, updated_at
FROM
    orgs
WHERE
    id = $1
    AND deleted_at IS NULL
LIMIT
    1
`

type GetOrgByIdRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetOrgById(ctx context.Context, id pgtype.UUID) (GetOrgByIdRow, error) {
	row := q.db.QueryRow(ctx, getOrgById, id)
	var i GetOrgByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT
    id, name, slug, created_at, updated_at
FROM
    orgs
WHERE
    slug = $1
    AND deleted_at IS NULL
LIMIT
    1
`

type GetOrgBySlugRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (GetOrgBySlugRow, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i GetOrgBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT
    om.org_id, om.user_id, om.role, om.joined_at,
    u.email, u.display_name
FROM
    org_members om
    JOIN users u ON u.id = om.user_id
WHERE
    om.org_id = $1
    AND om.user_id = $2
LIMIT
    1
`

type GetOrgMemberParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type GetOrgMemberRow struct {
	OrgID       pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Role        OrgRole            `db:"role" json:"role"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (GetOrgMemberRow, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i GetOrgMemberRow
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const listOrg = `-- name: ListOrg :many
SELECT
    id, name, slug, created_at, updated_at
FROM
    orgs
WHERE
    deleted_at IS NULL
    AND ($1::uuid IS NULL OR id = $1)
    AND ($2::uuid IS NULL OR id IN (
        SELECT org_id FROM org_members WHERE user_id = $2
    ))
ORDER BY
    created_at DESC
`

type ListOrgParams struct {
	Column1 pgtype.UUID `db:"column_1" json:"column_1"`
	Column2 pgtype.UUID `db:"column_2" json:"column_2"`
}

type ListOrgRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListOrg(ctx context.Context, arg ListOrgParams) ([]ListOrgRow, error) {
	rows, err := q.db.Query(ctx, listOrg, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgRow{}
	for rows.Next() {
		var i ListOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT
    om.org_id, om.user_id, om.role, om.joined_at,
    u.email, u.display_name
FROM
    org_members om
    JOIN users u ON u.id = om.user_id
WHERE
    om.org_id = $1
    AND ($2::text = '' OR u.email ILIKE '%' || $2 || '%')
    AND ($3::text = '' OR u.display_name ILIKE '%' || $3 || '%')
ORDER BY
    om.joined_at DESC
LIMIT  $4
OFFSET $5
`

type ListOrgMembersParams struct {
	OrgID   pgtype.UUID `db:"org_id" json:"org_id"`
	Column2 string      `db:"column_2" json:"column_2"`
	Column3 string      `db:"column_3" json:"column_3"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListOrgMembersRow struct {
	OrgID       pgtype.UUID        `db:"org_id" json:"org_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Role        OrgRole            `db:"role" json:"role"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, arg ListOrgMembersParams) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (
    SELECT 1 FROM orgs WHERE slug = $1 AND deleted_at IS NULL
)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs
SET
    name = COALESCE(NULLIF($1, ''), name),
    slug = COALESCE(NULLIF($2, ''), slug),
    updated_at = NOW()
WHERE
    id = $3
    AND deleted_at IS NULL
RETURNING
    id, name, slug, created_at, updated_at
`

type UpdateOrgParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	ID      pgtype.UUID `db:"id" json:"id"`
}

type UpdateOrgRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (UpdateOrgRow, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.Column1, arg.Column2, arg.ID)
	var i UpdateOrgRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :one
UPDATE org_members
SET
    role = $3
WHERE
    org_id = $1
    AND user_id = $2
RETURNING
    org_id, user_id, role, joined_at
`

type UpdateOrgMemberRoleParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Role   OrgRole     `db:"role" json:"role"`
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
