// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT
    COUNT(*)
FROM
    users
WHERE
    deleted_at IS NULL
    AND ($1::text = '' OR email ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR display_name ILIKE '%' || $2 || '%')
`

type CountUsersParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, display_name, password_hash)
VALUES
    ($1, $2, $3)
RETURNING
    id, email, display_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	DisplayName  string `db:"display_name" json:"display_name"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

type CreateUserRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET
    deleted_at = NOW()
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
    id, email, display_name, created_at, updated_at
FROM
    users
WHERE
    id = $1
    AND deleted_at IS NULL
LIMIT
    1
`

type GetUserRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, email, display_name, created_at, updated_at
FROM
    users
WHERE
    email = $1
    AND deleted_at IS NULL
LIMIT
    1
`

type GetUserByEmailRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, email, display_name, created_at, updated_at
FROM
    users
WHERE
    deleted_at IS NULL
    AND ($1::text = '' OR email ILIKE '%' || $1 || '%')
    AND ($2::text = '' OR display_name ILIKE '%' || $2 || '%')
ORDER BY
    created_at DESC
LIMIT  $3
OFFSET $4
`

type ListUsersParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type ListUsersRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    display_name = COALESCE(NULLIF($1, ''), display_name),
    password_hash = COALESCE(NULLIF($2, ''), password_hash),
    updated_at = NOW()
WHERE
    id = $3
    AND deleted_at IS NULL
RETURNING
    id, email, display_name, created_at, updated_at
`

type UpdateUserParams struct {
	Column1 interface{} `db:"column_1" json:"column_1"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	ID      pgtype.UUID `db:"id" json:"id"`
}

type UpdateUserRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Column1, arg.Column2, arg.ID)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
