// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (org_id, key, name, description, visibility)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrgID       pgtype.UUID       `db:"org_id" json:"org_id"`
	Key         string            `db:"key" json:"key"`
	Name        string            `db:"name" json:"name"`
	Description pgtype.Text       `db:"description" json:"description"`
	Visibility  ProjectVisibility `db:"visibility" json:"visibility"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrgID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
UPDATE projects
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
FROM projects
WHERE org_id = $1 AND key = $2 AND deleted_at IS NULL
`

type GetProjectByKeyParams struct {
	OrgID pgtype.UUID `db:"org_id" json:"org_id"`
	Key   string      `db:"key" json:"key"`
}

func (q *Queries) GetProjectByKey(ctx context.Context, arg GetProjectByKeyParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, arg.OrgID, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteProject, id)
	return err
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
FROM projects
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectVisibility = `-- name: UpdateProjectVisibility :one
UPDATE projects
SET visibility = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

type UpdateProjectVisibilityParams struct {
	ID         pgtype.UUID       `db:"id" json:"id"`
	Visibility ProjectVisibility `db:"visibility" json:"visibility"`
}

func (q *Queries) UpdateProjectVisibility(ctx context.Context, arg UpdateProjectVisibilityParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectVisibility, arg.ID, arg.Visibility)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
