// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (org_id, key, name, description, visibility)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrgID       pgtype.UUID       `db:"org_id" json:"org_id"`
	Key         string            `db:"key" json:"key"`
	Name        string            `db:"name" json:"name"`
	Description pgtype.Text       `db:"description" json:"description"`
	Visibility  ProjectVisibility `db:"visibility" json:"visibility"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrgID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
UPDATE projects
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
FROM projects
WHERE org_id = $1 AND key = $2 AND deleted_at IS NULL
`

type GetProjectByKeyParams struct {
	OrgID pgtype.UUID `db:"org_id" json:"org_id"`
	Key   string      `db:"key" json:"key"`
}

func (q *Queries) GetProjectByKey(ctx context.Context, arg GetProjectByKeyParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, arg.OrgID, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteProject, id)
	return err
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
FROM projects
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrgPaged = `-- name: ListProjectsByOrgPaged :many
WITH filtered_projects AS (
  SELECT
    id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at,
    COUNT(*) OVER () as total_count
  FROM
    projects
  WHERE
    deleted_at IS NULL
    AND (array_length($1::uuid[], 1) IS NULL OR org_id = ANY($1::uuid[]))
    AND (array_length($2::uuid[], 1) IS NULL OR id = ANY($2::uuid[]))
    AND ($3::text = '' OR name ILIKE '%' || $3 || '%')
)
SELECT
  id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at, total_count
FROM
  filtered_projects
ORDER BY
  created_at DESC
LIMIT $4
OFFSET $5
`

type ListProjectsByOrgPagedParams struct {
	Column1 []pgtype.UUID `db:"column_1" json:"column_1"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
	Column3 string        `db:"column_3" json:"column_3"`
	Limit   int32         `db:"limit" json:"limit"`
	Offset  int32         `db:"offset" json:"offset"`
}

type ListProjectsByOrgPagedRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OrgID       pgtype.UUID        `db:"org_id" json:"org_id"`
	Key         string             `db:"key" json:"key"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	Visibility  ProjectVisibility  `db:"visibility" json:"visibility"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TotalCount  int64              `db:"total_count" json:"total_count"`
}

func (q *Queries) ListProjectsByOrgPaged(ctx context.Context, arg ListProjectsByOrgPagedParams) ([]ListProjectsByOrgPagedRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrgPaged,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsByOrgPagedRow{}
	for rows.Next() {
		var i ListProjectsByOrgPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectVisibility = `-- name: UpdateProjectVisibility :one
UPDATE projects
SET visibility = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, key, name, description, visibility, created_at, updated_at, deleted_at
`

type UpdateProjectVisibilityParams struct {
	ID         pgtype.UUID       `db:"id" json:"id"`
	Visibility ProjectVisibility `db:"visibility" json:"visibility"`
}

func (q *Queries) UpdateProjectVisibility(ctx context.Context, arg UpdateProjectVisibilityParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectVisibility, arg.ID, arg.Visibility)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
