// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TicketPriority string

const (
	TicketPriorityLow      TicketPriority = "low"
	TicketPriorityMedium   TicketPriority = "medium"
	TicketPriorityHigh     TicketPriority = "high"
	TicketPriorityCritical TicketPriority = "critical"
)

func (e *TicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketPriority(s)
	case string:
		*e = TicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketPriority: %T", src)
	}
	return nil
}

type NullTicketPriority struct {
	TicketPriority TicketPriority `json:"ticket_priority"`
	Valid          bool           `json:"valid"` // Valid is true if TicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketPriority), nil
}

type TicketType string

const (
	TicketTypeBug   TicketType = "bug"
	TicketTypeStory TicketType = "story"
	TicketTypeTask  TicketType = "task"
	TicketTypeEpic  TicketType = "epic"
)

func (e *TicketType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketType(s)
	case string:
		*e = TicketType(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketType: %T", src)
	}
	return nil
}

type NullTicketType struct {
	TicketType TicketType `json:"ticket_type"`
	Valid      bool       `json:"valid"` // Valid is true if TicketType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketType) Scan(value interface{}) error {
	if value == nil {
		ns.TicketType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketType), nil
}

type Ticket struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ProjectID     pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketNumber  int32              `db:"ticket_number" json:"ticket_number"`
	Key           string             `db:"key" json:"key"`
	SprintID      pgtype.UUID        `db:"sprint_id" json:"sprint_id"`
	BoardID       pgtype.UUID        `db:"board_id" json:"board_id"`
	BoardColumnID pgtype.UUID        `db:"board_column_id" json:"board_column_id"`
	Type          TicketType         `db:"type" json:"type"`
	Priority      TicketPriority     `db:"priority" json:"priority"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	AssigneeID    pgtype.UUID        `db:"assignee_id" json:"assignee_id"`
	ReporterID    pgtype.UUID        `db:"reporter_id" json:"reporter_id"`
	EpicID        pgtype.UUID        `db:"epic_id" json:"epic_id"`
	ParentID      pgtype.UUID        `db:"parent_id" json:"parent_id"`
	StoryPoints   pgtype.Int4        `db:"story_points" json:"story_points"`
	DueDate       pgtype.Date        `db:"due_date" json:"due_date"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
