// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    project_id,
    ticket_number,
    key,
    type,
    priority,
    title,
    description,
    reporter_id,
    assignee_id,
    story_points,
    due_date
)
VALUES (
    $1,
    (SELECT next_number - 1 FROM ticket_counters WHERE project_id = $1),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
`

type CreateTicketParams struct {
	ProjectID   pgtype.UUID    `db:"project_id" json:"project_id"`
	Key         string         `db:"key" json:"key"`
	Type        TicketType     `db:"type" json:"type"`
	Priority    TicketPriority `db:"priority" json:"priority"`
	Title       string         `db:"title" json:"title"`
	Description pgtype.Text    `db:"description" json:"description"`
	ReporterID  pgtype.UUID    `db:"reporter_id" json:"reporter_id"`
	AssigneeID  pgtype.UUID    `db:"assignee_id" json:"assignee_id"`
	StoryPoints pgtype.Int4    `db:"story_points" json:"story_points"`
	DueDate     pgtype.Date    `db:"due_date" json:"due_date"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Key,
		arg.Type,
		arg.Priority,
		arg.Title,
		arg.Description,
		arg.ReporterID,
		arg.AssigneeID,
		arg.StoryPoints,
		arg.DueDate,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :one
UPDATE tickets
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, deleteTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const generateTicketKey = `-- name: GenerateTicketKey :one
SELECT generate_ticket_key($1)
`

func (q *Queries) GenerateTicketKey(ctx context.Context, pProjectID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, generateTicketKey, pProjectID)
	var generate_ticket_key string
	err := row.Scan(&generate_ticket_key)
	return generate_ticket_key, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
FROM tickets
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTicketByKey = `-- name: GetTicketByKey :one
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
FROM tickets
WHERE project_id = $1 AND key = $2 AND deleted_at IS NULL
`

type GetTicketByKeyParams struct {
	ProjectID pgtype.UUID `db:"project_id" json:"project_id"`
	Key       string      `db:"key" json:"key"`
}

func (q *Queries) GetTicketByKey(ctx context.Context, arg GetTicketByKeyParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByKey, arg.ProjectID, arg.Key)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteTicket = `-- name: HardDeleteTicket :exec
DELETE FROM tickets
WHERE id = $1
`

func (q *Queries) HardDeleteTicket(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteTicket, id)
	return err
}

const listTicketsByBoard = `-- name: ListTicketsByBoard :many
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
FROM tickets
WHERE board_id = $1 AND deleted_at IS NULL
ORDER BY ticket_number DESC
`

func (q *Queries) ListTicketsByBoard(ctx context.Context, boardID pgtype.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Key,
			&i.SprintID,
			&i.BoardID,
			&i.BoardColumnID,
			&i.Type,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.ReporterID,
			&i.EpicID,
			&i.ParentID,
			&i.StoryPoints,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByBoardColumn = `-- name: ListTicketsByBoardColumn :many
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
FROM tickets
WHERE board_column_id = $1 AND deleted_at IS NULL
ORDER BY ticket_number DESC
`

func (q *Queries) ListTicketsByBoardColumn(ctx context.Context, boardColumnID pgtype.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByBoardColumn, boardColumnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Key,
			&i.SprintID,
			&i.BoardID,
			&i.BoardColumnID,
			&i.Type,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.ReporterID,
			&i.EpicID,
			&i.ParentID,
			&i.StoryPoints,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByProject = `-- name: ListTicketsByProject :many
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
FROM tickets
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY ticket_number DESC
`

func (q *Queries) ListTicketsByProject(ctx context.Context, projectID pgtype.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Key,
			&i.SprintID,
			&i.BoardID,
			&i.BoardColumnID,
			&i.Type,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.ReporterID,
			&i.EpicID,
			&i.ParentID,
			&i.StoryPoints,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsBySprint = `-- name: ListTicketsBySprint :many
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
FROM tickets
WHERE project_id = $1 AND sprint_id = $2 AND deleted_at IS NULL
ORDER BY ticket_number DESC
`

type ListTicketsBySprintParams struct {
	ProjectID pgtype.UUID `db:"project_id" json:"project_id"`
	SprintID  pgtype.UUID `db:"sprint_id" json:"sprint_id"`
}

func (q *Queries) ListTicketsBySprint(ctx context.Context, arg ListTicketsBySprintParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsBySprint, arg.ProjectID, arg.SprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Key,
			&i.SprintID,
			&i.BoardID,
			&i.BoardColumnID,
			&i.Type,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.ReporterID,
			&i.EpicID,
			&i.ParentID,
			&i.StoryPoints,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsPaged = `-- name: ListTicketsPaged :many
WITH filtered_tickets AS (
    SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at,
           COUNT(*) OVER () as total_count
    FROM tickets
    WHERE deleted_at IS NULL
        AND (array_length($1::uuid[], 1) IS NULL OR project_id = ANY($1::uuid[]))
        AND (array_length($2::uuid[], 1) IS NULL OR id = ANY($2::uuid[]))
        AND (array_length($3::uuid[], 1) IS NULL OR sprint_id = ANY($3::uuid[]))
        AND (array_length($4::uuid[], 1) IS NULL OR board_id = ANY($4::uuid[]))
)
SELECT id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at, total_count FROM filtered_tickets
ORDER BY ticket_number DESC
LIMIT $5 OFFSET $6
`

type ListTicketsPagedParams struct {
	Column1 []pgtype.UUID `db:"column_1" json:"column_1"`
	Column2 []pgtype.UUID `db:"column_2" json:"column_2"`
	Column3 []pgtype.UUID `db:"column_3" json:"column_3"`
	Column4 []pgtype.UUID `db:"column_4" json:"column_4"`
	Limit   int32         `db:"limit" json:"limit"`
	Offset  int32         `db:"offset" json:"offset"`
}

type ListTicketsPagedRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ProjectID     pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketNumber  int32              `db:"ticket_number" json:"ticket_number"`
	Key           string             `db:"key" json:"key"`
	SprintID      pgtype.UUID        `db:"sprint_id" json:"sprint_id"`
	BoardID       pgtype.UUID        `db:"board_id" json:"board_id"`
	BoardColumnID pgtype.UUID        `db:"board_column_id" json:"board_column_id"`
	Type          TicketType         `db:"type" json:"type"`
	Priority      TicketPriority     `db:"priority" json:"priority"`
	Title         string             `db:"title" json:"title"`
	Description   pgtype.Text        `db:"description" json:"description"`
	AssigneeID    pgtype.UUID        `db:"assignee_id" json:"assignee_id"`
	ReporterID    pgtype.UUID        `db:"reporter_id" json:"reporter_id"`
	EpicID        pgtype.UUID        `db:"epic_id" json:"epic_id"`
	ParentID      pgtype.UUID        `db:"parent_id" json:"parent_id"`
	StoryPoints   pgtype.Int4        `db:"story_points" json:"story_points"`
	DueDate       pgtype.Date        `db:"due_date" json:"due_date"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	TotalCount    int64              `db:"total_count" json:"total_count"`
}

func (q *Queries) ListTicketsPaged(ctx context.Context, arg ListTicketsPagedParams) ([]ListTicketsPagedRow, error) {
	rows, err := q.db.Query(ctx, listTicketsPaged,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsPagedRow{}
	for rows.Next() {
		var i ListTicketsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TicketNumber,
			&i.Key,
			&i.SprintID,
			&i.BoardID,
			&i.BoardColumnID,
			&i.Type,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.AssigneeID,
			&i.ReporterID,
			&i.EpicID,
			&i.ParentID,
			&i.StoryPoints,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketBoard = `-- name: UpdateTicketBoard :one
UPDATE tickets
SET board_id = $2, board_column_id = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
`

type UpdateTicketBoardParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	BoardID       pgtype.UUID `db:"board_id" json:"board_id"`
	BoardColumnID pgtype.UUID `db:"board_column_id" json:"board_column_id"`
}

func (q *Queries) UpdateTicketBoard(ctx context.Context, arg UpdateTicketBoardParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketBoard, arg.ID, arg.BoardID, arg.BoardColumnID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTicketDetails = `-- name: UpdateTicketDetails :one
UPDATE tickets
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    type = COALESCE($4, type),
    priority = COALESCE($5, priority),
    assignee_id = COALESCE($6, assignee_id),
    story_points = COALESCE($7, story_points),
    due_date = COALESCE($8, due_date),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
`

type UpdateTicketDetailsParams struct {
	ID          pgtype.UUID    `db:"id" json:"id"`
	Title       string         `db:"title" json:"title"`
	Description pgtype.Text    `db:"description" json:"description"`
	Type        TicketType     `db:"type" json:"type"`
	Priority    TicketPriority `db:"priority" json:"priority"`
	AssigneeID  pgtype.UUID    `db:"assignee_id" json:"assignee_id"`
	StoryPoints pgtype.Int4    `db:"story_points" json:"story_points"`
	DueDate     pgtype.Date    `db:"due_date" json:"due_date"`
}

func (q *Queries) UpdateTicketDetails(ctx context.Context, arg UpdateTicketDetailsParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketDetails,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Priority,
		arg.AssigneeID,
		arg.StoryPoints,
		arg.DueDate,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTicketSprint = `-- name: UpdateTicketSprint :one
UPDATE tickets
SET sprint_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, ticket_number, key, sprint_id, board_id, board_column_id, type, priority, title, description, assignee_id, reporter_id, epic_id, parent_id, story_points, due_date, created_at, updated_at, deleted_at
`

type UpdateTicketSprintParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	SprintID pgtype.UUID `db:"sprint_id" json:"sprint_id"`
}

func (q *Queries) UpdateTicketSprint(ctx context.Context, arg UpdateTicketSprintParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketSprint, arg.ID, arg.SprintID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.Key,
		&i.SprintID,
		&i.BoardID,
		&i.BoardColumnID,
		&i.Type,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.AssigneeID,
		&i.ReporterID,
		&i.EpicID,
		&i.ParentID,
		&i.StoryPoints,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
